### ISSUE TITLE
[Feature Request] Generate schema from object (when checking matcher for the first time)

### ISSUE THREAD

**Issue by ilyazub** [americanexpress/jest-json-schema#1]
There is couple of tools for JSON schema validation by @bahmutov:
- [`bahmutov/schema-shot`](https://github.com/bahmutov/schema-shot)
- [`bahmutov/validate-by-example`](https://github.com/bahmutov/validate-by-example)

That tools depends on [`nijikokun/generate-schema`](https://github.com/nijikokun/generate-schema).

In the essence, [`bahmutov/schema-shot`](https://github.com/bahmutov/schema-shot) [records snapshot in the first time](https://github.com/bahmutov/schema-shot/blob/f02d6a803c40caa068fa6a9c74a7642f89204a46/README.md#example) and validates schema later on (by using [`bahmutov/validate-by-example`](https://github.com/bahmutov/validate-by-example)).

It would be great to introduce schema generation functionality into the [`jest-json-schema`](americanexpress/jest-json-schema).

What do you think?

**Comment by 10xLaCroixDrinker** [comment]
@ilyazub Great idea! Something like `expect(...).toMatchSchemaSnapshot()` would be really cool. Do you want to open a PR?

**Comment by ilyazub** [comment]
Yep, I'll try.

**Comment by ilyazub** [comment]
I'm going to close this one, since I'm totally satisfied with next approach:
```js
// https://github.com/nijikokun/generate-schema
import GenerateSchema from 'generate-schema';

describe(''generate-schema', () => {
  it('Generates JSON Schema from an object', () => {
    const obj = { answer: 42 }

    const schema = GenerateSchema.json(obj)
    expect(schema).toMatchSnapshot()
  })
})
```
