### ISSUE TITLE
jest-json-schema does not work when there is a missing field

### ISSUE THREAD

**Issue by fergadipa** [americanexpress/jest-json-schema#2]
Hi,

We found jest-json-schema does not work with missing field.
Endpoint : https://reqres.in/api/users/2
Method : GET
Actual json response : 

> { 
> id: 2,
> first_name: 'Janet',
> last_name: 'Weaver',
> avatar:'https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg'
> }

The code:
```
const { matchers } = require('jest-json-schema');
expect.extend(matchers);
const supertest = require('supertest');
const env = require('dotenv').config();
const api = supertest(process.env.API_BASE_URL);
const getSingleUser = id => api.get(`/users/${id}`)
  .set('Content-Type', 'application/json')
  .set('Accept', 'application/json');
let response;
describe('Test User', () => {
  test('Get single user dengan id 2', async () => {
    response = await getSingleUser(2);
    expect(response.status, 'Ini harus response 200').toBe(200);
    console.log(response.body.data);
    const schemaDetailUser = {
      type: 'object',
      required: ['first_name', 'last_name', 'avatar'],
      properties: {
        first_name: { type: 'string' },
        last_name: { type: 'string' },
        avatar: { type: 'string' },
      },
    };
    expect(response.body.data).toMatchSchema(schemaDetailUser);
  });
});
```
We expect that there will be an error occured because the 'id' field is missed.
But actually it does not display a error.
Or do I missed something?

Thank you

**Comment by anescobar1991** [comment]
You don't have `id` included in the `required` array and so your schema is not actually expecting `id` to be a required field.

**Comment by fergadipa** [comment]
Yes, that's what I mean. So I can add additionalProperties: false 
Thank you @anescobar1991
