### ISSUE TITLE
Not working with typescript test file

### ISSUE THREAD

**Issue by siddharth-dmart** [americanexpress/jest-json-schema#29]
Hi,

When test case is in typescript, the toMatchSchema option does work.
I have imported and exteded the matchers as instructed.
Getting the following error -
Property 'toMatchSchema' does not exist on type 'JestMatchersShape<Matchers<void, any>, Matchers<Promise<void>, any>>'.ts(2339)

Although, it works perfectly if I change my file back to plain javascript.

**Comment by AvantaR** [comment]
Same here.

**Comment by imSidJ** [comment]
This gets fixed after installing @types/jest-json-schema

**Comment by nellyk** [comment]
thank you!

**Comment by AvantaR** [comment]
> This gets fixed after installing @types/jest-json-schema

Omg, I feel so stupid now, thank you!

**Comment by Zubnix** [comment]
Might be a good idea to add this to the docs.

**Comment by nellyk** [comment]
@Zubnix  great suggestion we are open to PRs :-)
