### ISSUE TITLE
How can you set the AJV to use different schema versions

### ISSUE THREAD

**Issue by yotta-raj** [americanexpress/jest-json-schema#43]
In the AJV, to use the standard Draft07 
`const Ajv = require("ajv")`

but in the documentation of AJVm you can set to use the 2019 version? 
const Ajv2019 = require("ajv/dist/2019")

Is this possible using this package?

**Comment by 10xLaCroixDrinker** [comment]
Not currently, but open to adding it if you'd like to submit a PR 🙂

**Comment by 10xLaCroixDrinker** [comment]
#44 added this feature
